version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sellbie
      POSTGRES_PASSWORD: sellbie
      POSTGRES_DB: sellbie
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: